
//get all users
GET http://localhost:3000/api/users

###
//get one user by uid
GET http://localhost:3000/api/users/5547b445-284e-4870-8a29-766285aa8533


//create account
###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
  "name": "tit boy",
  "email": "bazooka",
  "password": "123"
}

//login
###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
   "email": "bazooka",
  "password": "123"
}



//update account
###
PATCH http://localhost:3000/api/users/07a91edf-f8b7-41fe-b719-6db4b87544ad
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3YTkxZWRmLWY4YjctNDFmZS1iNzE5LTZkYjRiODc1NDRhZCIsIm5hbWUiOiJ5ZXJycnJycnQiLCJlbWFpbCI6ImJhem9va2EiLCJwYXNzd29yZCI6IiQyYiQxMCRYL0JCMFUwcWNpLndoVm9Ray5mV0llV21BOU1VRjkuQ0U0ck1mb2F4Zk1mWFVBRWFOWmd2cSIsInJvbGUiOiJVU0VSIiwiY3JlYXRlZEF0IjoiMjAyMi0wOS0yNlQxNzoyOTo0Ny4xOThaIiwiaWF0IjoxNjY0MjE0NjUyfQ.8sevAEapT1NCOMn0MG3eXzqxdbJhBQJJrco9siq2454

{
  "name": "dumbledore"
}

###
//Delete User
DELETE http://localhost:3000/api/users/b1a6c635-8b17-4d0a-977b-f6f7c8409f0f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5YWI1MGRlLWU4NWMtNGUxYS1hNDEyLTdlMjJjM2Q0MzQzMSIsIm5hbWUiOiJKYW1lcyIsImVtYWlsIjoiY2hpbXBib295QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHlVVU5tSlFGUy5uSlc2cFc2UzRWa2VLbHBSaEFFV0RuYzliWlVLQmczYU9oVkwvVGFON2lpIiwicm9sZSI6IlVTRVIiLCJjcmVhdGVkQXQiOiIyMDIyLTA5LTI2VDE2OjI2OjU1LjA3MFoiLCJpYXQiOjE2NjQyMTAxNDV9.Cio5-Y8kjbyNJOGDfxItRM5jJpiJX8CTw0PUazOPTNo
